apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: NodePort  # Service type
  ports:
    - nodePort: 31001
      port: 8080       # service port
      targetPort: 80   # container port
      protocol: TCP
      name: http
  selector:
    app: nginx
    
  